In [76]:
import  pandas as pd
import numpy as np

In [77]:
#pip install scikit-learn
df = pd.read_csv('https://pycourse.s3.amazonaws.com/temperature.csv')
df

date  temperatura classification
0  2020-01-01         29.1         quente
1  2020-02-01         31.2   muito quente
2  2020-03-01         28.5         quente
3  2020-04-01         28.0         quente
4  2020-05-01         24.0    confortavel
5  2020-06-01         20.0           frio

In [78]:
# Criar um modelo de machine learning para prever a classe de temperatura (Frio, Bom, Quente) baseado na temperatura;

# x  = features (variáveis preditoras) y = target (variável target)

x = df["temperatura"].values
y = df["classification"].values

In [79]:
# Criar modelo de classificação usando pré-processamento

from sklearn.preprocessing import LabelEncoder

# Transformar as classes em valores numéricos, facilitando a classificação

le = LabelEncoder() # Instanciando o objeto LabelEncoder
y = le.fit_transform(y) # Transformando as classes em valores numéricos


#Classes numéricas (0, 1, 2, 3) ->  0 = confortável, 1 = frio, 3 = quente , 2 = muito quente

print(y)

[3 2 3 3 0 1]


In [80]:
# Usar modelo de regressão logística para classificação

from sklearn.linear_model import LogisticRegression

# Regressão logística é um algoritmo de classificação binária (duas classes) que usa uma função sigmoide para classificar os dados
# Por que regressão logística? Porque a variável target é categórica (Frio, Bom, Quente)

lr = LogisticRegression() # Instanciando o objeto LogisticRegression

# Treinar o modelo

lr.fit(x.reshape(-1, 1), y) # Treinando o modelo --> encontra os coeficientes (a e b) da equação da reta para melhor descrever a regressão

# dados da regressão

print("\ncoeficiente angular\n",lr.coef_) # coeficiente angular da reta
print("\ncoeficiente linear\n",lr.intercept_) # coeficiente linear da reta


# Cada coeficiente corresponde a uma classe (Frio, Bom, Quente, muito quente)


coeficiente angular
 [[-0.37726722]
 [-0.92641757]
 [ 1.05225353]
 [ 0.25143127]]

coeficiente linear
 [ 10.94763943  23.2334519  -29.40283192  -4.77825942]


In [81]:
# Testar modelo em instancias novas criadas aleatoriamente

x_test = np.linspace(start = 0, stop = 45, num = 100) # Criando 1000 valores de temperatura entre -10 e 50

print("Valores de temperatura criados:\n")
print(x_test)


Valores de temperatura criados:

[ 0.          0.45454545  0.90909091  1.36363636  1.81818182  2.27272727
  2.72727273  3.18181818  3.63636364  4.09090909  4.54545455  5.
  5.45454545  5.90909091  6.36363636  6.81818182  7.27272727  7.72727273
  8.18181818  8.63636364  9.09090909  9.54545455 10.         10.45454545
 10.90909091 11.36363636 11.81818182 12.27272727 12.72727273 13.18181818
 13.63636364 14.09090909 14.54545455 15.         15.45454545 15.90909091
 16.36363636 16.81818182 17.27272727 17.72727273 18.18181818 18.63636364
 19.09090909 19.54545455 20.         20.45454545 20.90909091 21.36363636
 21.81818182 22.27272727 22.72727273 23.18181818 23.63636364 24.09090909
 24.54545455 25.         25.45454545 25.90909091 26.36363636 26.81818182
 27.27272727 27.72727273 28.18181818 28.63636364 29.09090909 29.54545455
 30.         30.45454545 30.90909091 31.36363636 31.81818182 32.27272727
 32.72727273 33.18181818 33.63636364 34.09090909 34.54545455 35.
 35.45454545 35.90909091 36.363636

In [82]:
y_pred = lr.predict(x_test.reshape(-1, 1)) # Fazendo a predição para os valores de temperatura criados

print("\nValores preditos para os dados criados (Interpretação númerica):\n")
print(y_pred) # valores preditos para os dados porém de forma numérica

y_pred = le.inverse_transform(y_pred) # Transformando os valores numéricos em forma categorica
print("\nValores preditos para os dados criados (Interpretação categórica):\n")
print(y_pred) # valores preditos para os dados porém de forma categórica


Valores preditos para os dados criados (Interpretação númerica):

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

Valores preditos para os dados criados (Interpretação categórica):

['frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio'
 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio'
 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio'
 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio'
 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio' 'frio'
 'confortavel' 'confortavel' 'confortavel' 'confortavel' 'confortavel'
 'confortavel' 'quente' 'quente' 'quente' 'quente' 'quente' 'quente'
 'quente' 'quente' 'quente' 'quente' 'quente' 'quente' 'muito quente'
 'muito quente' 'muito quente' 'muito quente' 'muito quente'
 'muito quente' 'muito quente' 'mu

In [83]:
# Criando um dataframe com os valores de temperatura e classificação
SinteticDf = pd.DataFrame({'Temperatura': x_test, 'Classificação': y_pred})
#Salvando o dataframe em um arquivo csv
SinteticDf.to_csv('SinteticDf.csv', index=False)

In [86]:
# Criar função para classificar a temperatura

def ClassifyTemperature(temperature):
    
    #Usar o modelo de regressão logística para classificar a temperatura
    
    formatedTemperature = np.array(float(temperature)).reshape(-1, 1) # Transformando a temperatura em um array de uma dimensão
    
    numericClassification = lr.predict(formatedTemperature) # Classificando a temperatura  

    
    categoricalClassification = le.inverse_transform(numericClassification) # Transformando a classificação numérica em categórica   

    
    return categoricalClassification[0] # Retornando a classificação categórica 
    
    

In [87]:
ClassifyTemperature(22)

'frio'