In [1]:
import numpy as np

### Criação de arrays e Matrizes

In [2]:
    # Criando um array de forma explicita

v = np.array([1,2,3,4,5,6,7,8,9,10])


print(v)
print()

    # Criando Matriz de forma explicita

v = np.array([[1,2,3],[4,5,6],[7,8,9]]) # M3x3

print(v)
print()
print()

    # Criar array vazio 

v = np.empty(10) # Argumento é o tamanho do array 

print(v) # Retorna --> Lixo de memória, espaço alocado mas não inicializado !!
print()

    # Criar Matriz vazia

#M3x3 Mij = Vazio
v = np.empty([3,3])  # Argumento é o tamanho da matriz para cada uma das dimensões (pode ser uma variável np.array([x,y]))) 
print(v) # Retorna --> Lixo de memória, espaço alocado mas não inicializado !!
print()
print()
    ## Criar array preenchido 

v = np.zeros(10) # Argumento é o tamanho do array
print(v)
print()

v = np.ones(10) # Argumento é o tamanho do array
print(v)
print()

    # Criar Matriz preenchida
    
v = np.zeros([3,3]) # Argumento é o tamanho da matriz para cada uma das dimensões (pode ser uma variável np.array([x,y])))
print(v)
print()
print()

v = np.ones([3,3]) # Argumento é o tamanho da matriz para cada uma das dimensões (pode ser uma variável np.array([x,y])))
print(v)
print()
print()

v = np.eye(3) # Matriz identidade 3x3
print(v)
print()
print()





[ 1  2  3  4  5  6  7  8  9 10]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[6.23042070e-307 4.67296746e-307 1.69121096e-306 4.67293691e-307
 2.67019592e-306 1.42413555e-306 1.78019082e-306 1.37959740e-306
 6.23057349e-307 1.42419530e-306]

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 7.35e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




### Iterar sobre  array e matrizes

In [3]:
v = np.zeros(10)
w = np.zeros([3,3])

# Iterando sobre os elementos de um array

for i in np.arange(0,10,1): # np.arange(inicio, fim, passo) para iterar com indice i
    v[i] = i+1
    
print(v)
print()

for i in np.nditer(v): # para iterar sobre os valores do array
    print(i)
print()
# Iterando sobre os elementos de uma matriz

for i in np.arange(0,3,1):
    for j in np.arange(0,3,1):
        w[i,j] = i+j
        
print(w)
print()

for i in np.nditer(w):
    print(i)



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]

0.0
1.0
2.0
1.0
2.0
3.0
2.0
3.0
4.0


### Inserir e remover elementos de Arrays e Matrizes

In [4]:
#Inserção em arrays

print("Array Original: ", v)

# Inserir (append) valores em um array --> Insere_Final(int vetor, int valor)
v = np.append(v, 11) # array aumenta de tamanho e insere o valor 11 com um encadeamento
print("Apos inserção: ",v)
print()


# Inserir (insert) valores em um array --> Insere_Posicao(int vetor, int posicao, int valor)
v = np.insert(v, 0, 0) # array aumenta de tamanho e insere o valor 0 na posição 0 
print("Apos inserção: ",v)
#caso a posição do novo elemento coincida com a posição de um elemento já existente, o novo elemento é inserido antes
v = np.insert(v, 0, -1) # array aumenta de tamanho e insere o valor 0 na posição 0
print("Apos inserção com colisão: ",v)
print()

#Inserção em Matrizes

print("Matriz Original: ", w)

# Inserir (append) valores em um array --> Insere_Final(int vetor, int valor)
w = np.append(w, [[1,1,1]], axis=0) # array aumenta de tamanho e insere o valor 11 com um encadeamento
print("Apos inserção: ",w)
print()

# Inserir (insert) valores em um array --> Insere_Posicao(int vetor, int posicao, int valor)
w = np.insert(w, 0, [[0,0,0]], axis=0) # array aumenta de tamanho e insere o valor 0 na posição 0
print("Apos inserção: ",w)
#caso a posição do novo elemento coincida com a posição de um elemento já existente, o novo elemento é inserido antes
w = np.insert(w, 0, [[-1,-1,-1]], axis=0) # array aumenta de tamanho e insere o valor 0 na posição 0
print("Apos inserção com colisão: ",w)



Array Original:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Apos inserção:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Apos inserção:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Apos inserção com colisão:  [-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Matriz Original:  [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
Apos inserção:  [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [1. 1. 1.]]

Apos inserção:  [[0. 0. 0.]
 [0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [1. 1. 1.]]
Apos inserção com colisão:  [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 0.  1.  2.]
 [ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 1.  1.  1.]]


In [5]:

#Remoção em arrays

print("Array Original: ", v)
print()

# Remover (delete) valores em um array --> Remove_Posicao(int vetor, int posicao)
v = np.delete(v, 0) # array diminui de tamanho e remove o valor da posição 0
print("Apos remoção: ",v)
print()
# remover passando um array de posições
v = np.delete(v, [0,1,2]) # array diminui de tamanho e remove os valores das posições 0, 1 e 2
print("Apos remoção: ",v)
print()
# remover passando o item a ser removido
v  = np.delete(v, np.where(v == 11)) # array diminui de tamanho e remove o valor 11
print("Apos remoção: ",v)
print()


#Remoção em Matrizes

print("Matriz Original: ", w)
print()

# Remover (delete) valores em um array --> Remove_Posicao(int vetor, int posicao)
w = np.delete(w, 0, axis=0) # array diminui de tamanho e remove o valor da posição 0
print("Apos remoção: ",w)
print()
# remover passando um array de posições
w = np.delete(w, [0,1,2], axis=0) # array diminui de tamanho e remove os valores das posições 0, 1 e 2
print("Apos remoção: ",w)
print()

#Remover passando o item a ser removido
w = np.delete(w, np.where(w == 1)) # array diminui de tamanho e remove o valor 11
print("Apos remoção: ",w)





Array Original:  [-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Apos remoção:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Apos remoção:  [ 3.  4.  5.  6.  7.  8.  9. 10. 11.]

Apos remoção:  [ 3.  4.  5.  6.  7.  8.  9. 10.]

Matriz Original:  [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 0.  1.  2.]
 [ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 1.  1.  1.]]

Apos remoção:  [[0. 0. 0.]
 [0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [1. 1. 1.]]

Apos remoção:  [[2. 3. 4.]
 [1. 1. 1.]]

Apos remoção:  [1. 1. 1.]


### Operação Aritméticas

In [6]:
# Soma subtração multiplicação e divisão de arrays

u = np.array([1,2,3,4,5,6,7,8,9,10])
v = np.array([1,2,3,4,5,6,7,8,9,10])

# Operações entre arrays de mesmo tamanho, aplica a operação elemento a elemento
print("Operações entre vetores:\n")
print("soma:\n")
print(u+v) 
print("subtração:\n")
print(u-v)
print("multiplicação:\n")
print(u*v)
print("divisão:\n")
print(u/v)

#Broadcasting de arrays (soma, subtração, multiplicação e divisão de arrays de tamanhos diferentes)
print("\nOperações entre vetores de tamanhos diferentes:\n")

print("soma:\n")
print(u+1) # adiciona 1 a cada elemento do array
print("subtração:\n")
print(u-1) # subtrai 1 de cada elemento do array
print("multiplicação:\n")
print(u*2) # multiplica cada elemento do array por 2
print("divisão:\n")
print(u/2) # divide cada elemento do array por 2





# Soma subtração multiplicação e divisão de matrizes

t = np.array([[1,2,0],[1,5,3],[-1,2,2]])
z = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nOperações entre matrizes:\n")
print("soma:\n")
print(t+z)
print("subtração:\n")
print(t-z)
print("multiplicação elemento por elemento:\n")
print(t*z) # Multiplica elemento a elemento
print("multiplicação de matrizes:\n")
print(np.dot(t,z)) # Multiplica matrizes (linhas de t por colunas de z)
print("divisão elemento por elemento:\n")
print(t/z) # Divide elemento a elemento








Operações entre vetores:

soma:

[ 2  4  6  8 10 12 14 16 18 20]
subtração:

[0 0 0 0 0 0 0 0 0 0]
multiplicação:

[  1   4   9  16  25  36  49  64  81 100]
divisão:

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Operações entre vetores de tamanhos diferentes:

soma:

[ 2  3  4  5  6  7  8  9 10 11]
subtração:

[0 1 2 3 4 5 6 7 8 9]
multiplicação:

[ 2  4  6  8 10 12 14 16 18 20]
divisão:

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

Operações entre matrizes:

soma:

[[ 2  4  3]
 [ 5 10  9]
 [ 6 10 11]]
subtração:

[[ 0  0 -3]
 [-3  0 -3]
 [-8 -6 -7]]
multiplicação elemento por elemento:

[[ 1  4  0]
 [ 4 25 18]
 [-7 16 18]]
multiplicação de matrizes:

[[ 9 12 15]
 [42 51 60]
 [21 24 27]]
divisão elemento por elemento:

[[ 1.          1.          0.        ]
 [ 0.25        1.          0.5       ]
 [-0.14285714  0.25        0.22222222]]


### Lógica Booleana

In [10]:
#Matriz Y

y  = np.array([[1,2,3],[4,5,6],[7,8,9]])


print("Logica Booleana\n")


print("Valores de y>0:")
restricao = y > 0 # retorna uma matriz booleana com True para os elementos que satisfazem a condição e False para os que não satisfazem
print(restricao)
print("Matriz com restrição:")
print(y[restricao])
print("Valores Par:")

rest = y % 2 == 0 # retorna uma matriz booleana com True para os elementos que satisfazem a condição e False para os que não satisfazem
print(rest)
print()
print(y[rest])

#Localiar indices de elementos que satisfazem uma condição

i,j = np.where(rest) # retorna os indices i e j dos elementos que satisfazem a condição

#Retornar lista com os pares i1 e j1 , i2 e j2, i3 e j3, ... , in e jn

print("Indices dos elementos pares:")
print(list(zip(i,j))) # zip retorna uma lista de tuplas com os elementos de i e j em pares

Logica Booleana

Valores de y>0:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Matriz com restrição:
[1 2 3 4 5 6 7 8 9]
Valores Par:
[[False  True False]
 [ True False  True]
 [False  True False]]

[2 4 6 8]
Indices dos elementos pares:
[(0, 1), (1, 0), (1, 2), (2, 1)]


### Ferramentas para Algebra Linear

In [ ]:
# Determinante de uma matriz

print("Ferramentas de Algebra Linear\n")

print("Determinante de uma matriz\n")
print(np.linalg.det(t))
print("Matriz transposta\n")




# Transposta de uma matriz

print(np.transpose(t))
print("Matriz transposta - v2\n")
print(t.T) # Transposta de uma matriz
print("Matriz inversa\n")


y = np.array([[1,2,0],[1,5,3],[-1,2,2]])
# Matriz inversa de y --> y**-1
print(np.linalg.inv(y))
print("Resolver sistema linear\n")

z = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Resolver o sistema x*y = z --> x = z*y**-1

print(np.dot(z,np.linalg.inv(y)))
print()




### Operações com Numpy

In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Mudar dimensão da matriz

print("Mudar dimensão da matriz\n")
# Possibilidades de mudança de dimensão: (3,3) --> (1,9) (3,3) (9,1) (1,1) (3,1) (1,3) (9,3) (3,9)
print(m.reshape(1,9)) # Transforma a matriz em um vetor de 1 linha e 9 colunas

print("Somar elementos de uma matriz:\n")
#todos os elementos
print("\nTodos os elementos: \n")
print(np.sum(m))
#somar elementos de determinada linha
print("\nLinha 1: \n")
print(np.sum(m[0,:]))
#ou passando o eixo
print("\nLinha 1 - parametro axis: \n")
print(np.sum(m, axis=0))


# Medidas estatísticas

#pode usar mesmas ideias de idexação e parametro axis usado no somatório !!!

print("Medidas estatísticas\n")
print("Média: \n")
print(np.mean(m))
print("Mediana: \n")
print(np.median(m))

